### ISSUE TITLE
Eventtypes/Actionstype: Lost Paramentries

### ISSUE THREAD

**Issue by Rushor** [Discover-/SAI-Editor#26]
Just like to report a minor issue while filling fields in eventparam_x/actionparam_x.
The values in these fields disappear after the comments were generated.

Example:
Before: http://pokit.org/get/?5fef3473ff692b6ab91c293d2da52db0.jpg
Creaturemodelfield has datas

 -> then after running the generating button

http://pokit.org/get/?c7590ccac58f76d65ecc713a8db0c620.jpg
Creaturemodelfield lost datas

This also happens with some eventparams.

Best regards :)

**Comment by Discover-** [comment]
Interesting. Will take a look after the new listview works again!

**Comment by Rushor** [comment]
thanks for the fast reply :D

**Comment by Gooyeth** [comment]
Same with 'Data' of ACTION_SET_DATA.

**Comment by Rushor** [comment]
i think it's only the param2 for all actiontypes, i have no problem with all other params

so:
action 53 > param2 > waypointentry
action11 > param2 > castflag

and so on

**Comment by Discover-** [comment]
Now we're talking! Thanks for that detail, that's going to help a lot.

**Comment by Rushor** [comment]
Thank you again so much!
