### ISSUE TITLE
Alt+F4 and menu option "Exit (Alt + F4)" disabled

### ISSUE THREAD

**Issue by tkrokli** [Discover-/SAI-Editor#29]
Version: 1.4.3 from http://www.trinitycore.org/f/files/file/17-sai-editor/
(I could not find which commit rev. hash the 1.4.3 version uses)

If you want to close the application, the only working option is the [X] in the top right corner.
The keyboard combo Alt+F4 and File menu option "Exit" does not react at all (disabled).

**Comment by Discover-** [comment]
Will be included once the new update is finally ready. Still a lot to do.

If you would like to help, there's a tedious task still on TODO which is creating a local database file for the 6.x expansion (DBC files, for example). Wotlk and cata are already done, MoP is not a requirement for this release.
