### ISSUE TITLE
Bug minimizing

### ISSUE THREAD

**Issue by Gooyeth** [Discover-/SAI-Editor#30]
**OS**: Windows 7 Ultimate x64
**Compiling**: Release/Debug - Mixed Platforms

When you minimize the window disappears, for example:

Open to SAI-Editor:

![SAI-Editor](http://i57.tinypic.com/1qlixc.png)

Minimizing:

![SAI-Editor Bug](http://i58.tinypic.com/mb0n5l.png)

**Comment by Rushor** [comment]
note: not reproducable on win 8 x64

**Comment by Discover-** [comment]
Thanks for the report. I was able to reproduce this on my laptop, which runs Windows 7. For some reason the tabcontrol's width and height get resized to 0 when minimizing the application.
