### ISSUE TITLE
Parameters dont work!

### ISSUE THREAD

**Issue by Orangs** [Discover-/SAI-Editor#34]
Hello,
i want edit my Smart_script bud TAB with Parameters doesnt work and when i want to execute script, some errors will show.
![image](https://cloud.githubusercontent.com/assets/2785697/10021528/b2493778-6148-11e5-87c7-880b5b90103c.png)
![image](https://cloud.githubusercontent.com/assets/2785697/10021544/c11e24d4-6148-11e5-8bcd-1922d7f458d0.png)

Previous versions like 1.3.0 working better or i dont know where is the problem...

**Comment by Discover-** [comment]
I am not getting this exception myself, ever. Can you paste the full error and upload it to pastebin please?

**Comment by Orangs** [comment]
Here is error log from SAI Editor. 
http://pastebin.com/JB9pPfy9

**Comment by Discover-** [comment]
I am not really sure what to do here. I didn't hear from anyone else having this issue and I am unable to reproduce on both Windows 7 and Windows 8. Are you sure you're on the latest version?

**Comment by Orangs** [comment]
I have only Windows 8, no Windows 8.1.... but another programs like Truice etc. is working very well. Your version 1.3.0 what i use, its works very well, but i cant find previous versions for download :/

**Comment by Discover-** [comment]
The tool is very, very different from Truice. Not really comparable.

Can anyone confirm they have the same issue as @Orangs?

**Comment by Orangs** [comment]
@Discover- you know all Requirements for SAI Editor? Like framework 4.5? Thanks for answer. I still looking for some solution for my problem :/

**Comment by Discover-** [comment]
.NET 4.5 is required, yes. Did you try a clean pull and install?

**Comment by Orangs** [comment]
Yes. I try clean install but again not working :cry:

**Comment by Faq** [comment]
Just paste your script, so can check if the same will happen.

**Comment by Orangs** [comment]
same error log like previous :crying_cat_face:

**Comment by Discover-** [comment]
What @Faq meant is if you could copy paste your SQL script that is causing issues in a pastebin and link it here.

**Comment by Orangs** [comment]
Still same error log. I dont know where is problem.
Same like previous http://pastebin.com/JB9pPfy9 :/

**Comment by Discover-** [comment]
The SQL script, not the error log.

**Comment by Orangs** [comment]
Here is SQL script http://pastebin.com/VHCBVdes
+ here is a little video preview, where you can see my problem with Parameters.

**Comment by Discover-** [comment]
The SQL script executes just fine for me. I do not get any errors thrown like your screenshot shows.
![](http://i.imgur.com/EiQts0Z.png)


Also, you have to pull a new version of the code for the refreshing issue (#36) to be fixed. This also seems like it is the only issue in the video.

Thanks for the reports and video! Very helpful and insightful. :+1:
