### ISSUE TITLE
Have to Click "Generate Comments" Every Time

### ISSUE THREAD

**Issue by Prodiege** [Discover-/SAI-Editor#36]
You have to click "Generate Comments" every time you want to see the Dynamic Script Information and the Parameters updated when selecting a new event. In the previous version you didn't have to do this

**Comment by Discover-** [comment]
Do you have the checkbox to automatically generate comments enabled?

**Comment by Prodiege** [comment]
Yes and it automatically generates the comments

**Comment by Discover-** [comment]
I don't understadn the issue you're having, in that case. When I have it enabled and I change something, it generates comments perfectly fine for me.

**Comment by Prodiege** [comment]
I didn't say anything about trouble generating comments. I said you have to click the "Generate Comments" button every time you want to see the Dynamic Script Information and Parameters changed to the current event you are clicking on. I screen recorded a video and it is uploading now to give you a better idea

**Comment by Prodiege** [comment]
Here it is https://www.youtube.com/watch?v=YJHQNVpS9nc&

**Comment by Discover-** [comment]
Ah, I see what you mean. That video was very helpful, thanks. Sadly it's an issue where VS WinForms sometimes discards events on some controls for no apparent reason. I've hardcoded the event linking in the code so it won't happen again.

**Comment by Discover-** [comment]
The new version has been uploaded.
