### ISSUE TITLE
can not open 

### ISSUE THREAD

**Issue by qyh214** [Discover-/SAI-Editor#37]
I do not know why and I have used 1.4.3 and well but 1.5.0 open it and can not open and not errors

win 10 x64

**Comment by Discover-** [comment]
I don't have access to a W10 machine at the moment. Is it related to the OS version or not, you think?

**Comment by qyh214** [comment]
I have test in win7 x64 but the ui do not show, can not operate, and there is no error……
maybe I miss something?
or for my language is Chinease and region is CN?
Close anti-virus software sai editor also invalid

**Comment by Discover-** [comment]
It also doesn't show on W7? That's interesting. Do you have access to an English machine of some kind to test it on?
