### ISSUE TITLE
Fields not updating

### ISSUE THREAD

**Issue by jbob0124** [Discover-/SAI-Editor#38]
When switching from say line 1 to line 3, none of the information updates.  The only way I have found to update the information is to click "generate comments".  Even when clicking on generate, the fields are slow to update.  Im using Win7 64bit, SAI-Editor 1.5 and SQLyog.  The databases seems fine, wow runs fine, auth and world.exe run fine.  Not sure if its me or something else.  The two screen shots are examples.  They show the same information even though different line items are selected.
![sai 1](https://cloud.githubusercontent.com/assets/4535046/11673176/ad1a0056-9de4-11e5-9343-2f8b46b3f4d0.PNG) 
![sai 3](https://cloud.githubusercontent.com/assets/4535046/11673180/b445ca9a-9de4-11e5-892a-0639f5ee8668.PNG)

EDIT:  I uninstalled the .exe I downloaded from TC and pulled and compiled my own.  Doing so seemed to clear up the issue, so it must be something that was recently fixed?

**Comment by Discover-** [comment]
Same issue as #36, fixed with 430b4112e2d78c928efb7f266a11be09fa5c037b. I haven't had time to release a new version yet, but I'll get to it as soon as I can. Thanks for the report though!

**Comment by Discover-** [comment]
The new version has been uploaded.

**Comment by jbob0124** [comment]
Will download now, thank you.
