### ISSUE TITLE
[1.5.1] Condition-Editor missing 2 SQL output options: NegativeCondition & ErrorType

### ISSUE THREAD

**Issue by tkrokli** [Discover-/SAI-Editor#42]
**SAI-Editor / Condition-Editor version:** 1.5.1

Maybe this is a minor detail (I don't know), but it would be very useful if Condition-Editor could add SQL output of the 2 condition options `NegativeCondition` and `ErrorType`, at least for TrinityCore `conditions` SQL scripts.

As it is now, the action button [**Generate SQL**] does not add these 2 options to the SQL output. The Condition-Editor only shows these 2 options in the [**Conditions overview**] tab.
(sorry for not pointing this detail out in the first version of this post)

At the moment, those 2 options are missing in the SQL output from Condition-Editor version 1.5.1.
(I don't know how much is involved to make this change, so if it is too much work, I don't blame you.) :)
***
edit: Added "Milestone" or points to this issue post:
- [X] Add `NegativeCondition` output to SQL (default: 0)
- [X] Add `ErrorType` output to SQL (default: 0)

**Comment by Discover-** [comment]
Thanks for the report.

Please let me know if it's working now. I don't have a proper environment setup at this moment so can't test it thoroughly.

**Comment by tkrokli** [comment]
Tested it now and it outputs both values and column names as expected. Thanks! :+1:
***
I should probably mention that there is no button or menu to set the `NegativeCondition` value in the GUI. Do you prefer to have that reported in a new issue, so you can close this one? :)

**Comment by Discover-** [comment]
Great to hear! :smile: 

As for the NegativeCondition, from what I remember this was more like an optional condition value rather than a new field or am I wrong? What I mean is that it was only used for a handful of condition types.

Would it be a good idea to put `NegativeCondition` input field right below the `ConditionValue3

**Comment by tkrokli** [comment]
It looks like there is space to put the GUI `NegativeCondition` selector above [Error type:] and [Error text id:] so those 2 controls get pushed down 1 place. I also think it is logical to find the `NegativeCondition` selector just behind the `ConditionValue1` selector. I hope this makes sense. Image:

![condition-editor](https://cloud.githubusercontent.com/assets/4903600/15326094/57352a7c-1c55-11e6-98ca-6558254f6807.png)

**Comment by Discover-** [comment]
How is this?

**Comment by tkrokli** [comment]
Will do a new pull and check. Reporting back after testing. :)

**Comment by tkrokli** [comment]
Hmm... I can't seem to open Condition-Editor after compiling the new version. Do I need to downgrade or upgrade my Visual Studio 2013 update 5 (or use VS2015) to make the current build work as .EXE ?

![sai-editor open conditions-editor](https://cloud.githubusercontent.com/assets/4903600/15335508/575a5a4c-1c7b-11e6-842e-064413b467bf.png)

Full output text: http://pastebin.com/bUuFXzgm (Condition-Editor Unhandled Exception)

**Comment by Discover-** [comment]
Oops, try now.

**Comment by tkrokli** [comment]
(Sorry for the delayed reply, I had a busy day driving around on Crete with my parents. :) )
Yes, it works now. The placing is good, I approve of your changes. :)

![condition-editor codition editing](https://cloud.githubusercontent.com/assets/4903600/15361508/6ddf97ba-1d1a-11e6-82c0-b301ce3ccef9.png)

I don't like being pedantic, but I usually am. If I may point out a detail regarding the selection of the upper right hand options [Gossip menu entry] and [Gossip menu text entry], I only get zero (0) as values instead of the actual `gossip_menu`.`entry` + `gossip_menu`.`text_id` as in this example:

![condition-editor conditions overview](https://cloud.githubusercontent.com/assets/4903600/15361666/18d9a9bc-1d1b-11e6-85db-b61c851e17fc.png)

1. This window needs to be larger (wider + higher) to show the bottom button options at all.

2. Maybe this window ( [Codition editing] + [Conditions overview] ) could be resizeable?

3. In the 3 lines in the image example above, I have manually entered the values for `gossip_menu`.`entry` + `gossip_menu`.`text_id` in line 1 and 2, because the Editor only adds 0, which are not part of the `gossip_menu` table. Line 3 shows the result from picking those values from the list selectors. Those values could in theory only be valid for `gossip_menu_option`, but not for `gossip_menu`.
```sql
SELECT * FROM `gossip_menu` WHERE `entry`= 0 AND `text_id` = 0;
```
```
 entry  text_id
------  -------
```
Result: (empty table)

If I may suggest a change, it would be that those 2 options change names if the user selects `SOURCE_TYPE_GOSSIP_MENU` (14), the names of those 2 options can be replaced with [Gossip menu entry] and [Gossip menu text_id]. In the same way, if the user selects `SOURCE_TYPE_GOSSIP_MENU_OPTION` (15), the names could reflect the actual table column names `gossip_menu_option.menu_id` and `gossip_menu_option.id` (you can of course choose to put your own version of the column names there, as long as it makes sense and refers to the actual column names).

***
Looking back at image 1 (Codition editing tab), may I suggest that the 3 lines below [Condition type] are by default labeled as `ConditionValue1`,`ConditionValue2`,`ConditionValue3` just like in the DB `conditions` table, and that the names change depending on the selected [Condition type]? (You can continue to use the existing behaviour that the ConditionValue2 and ConditionValue3 names are removed if they are not used in the selected Condition type.)

**Comment by tkrokli** [comment]
Maybe my latest comment is a bit much for this issue and that it should be moved to a new issue? :)

**Comment by tkrokli** [comment]
Never mind, I think my latest suggestions are way outside of this issue. I will remove this extra text in https://github.com/Discover-/SAI-Editor/issues/42#issuecomment-220045853 and move it to a new issue. Thanks a lot for keeping up your work on this. :+1:

**Comment by tkrokli** [comment]
New issue based on the content I moved: [**[Condition-Editor] : GUI + functionality changes wanted**](44) #44
