### ISSUE TITLE
[Condition-Editor] : GUI + functionality changes wanted

### ISSUE THREAD

**Issue by tkrokli** [Discover-/SAI-Editor#44]
(issue content moved here from issue #42 because the original issue was solved)

![condition-editor codition editing](https://cloud.githubusercontent.com/assets/4903600/15361508/6ddf97ba-1d1a-11e6-82c0-b301ce3ccef9.png)

I don't like being pedantic, but I usually am. If I may point out a detail regarding the selection of the upper right hand options [Gossip menu entry] and [Gossip menu text entry], I only get zero (0) as values instead of the actual `gossip_menu`.`entry` + `gossip_menu`.`text_id` as in this example:

![condition-editor conditions overview](https://cloud.githubusercontent.com/assets/4903600/15361666/18d9a9bc-1d1b-11e6-85db-b61c851e17fc.png)

1. This window needs to be larger (higher) to show the bottom button options at all.

2. Maybe Condition-Editor ( [Codition editing] + [Conditions overview] ) could be resizeable?

3. In the 3 lines in the image example above, I have manually entered the values for `gossip_menu`.`entry` (`SourceGroup`) + `gossip_menu`.`text_id` (`SourceEntry`) in line 1 and 2, because the Editor only adds 0, which is not a valid value in the `gossip_menu` table. Line 3 shows the result from picking those values from the list selectors. Those values could in theory be valid for `gossip_menu_option`, but not for `gossip_menu`.
```sql
SELECT * FROM `gossip_menu` WHERE `entry`= 0 AND `text_id` = 0;
```
```
 entry  text_id
------  -------
```
Result: (empty table)

Likewise, for `gossip_menu_option`, the values 0,0 will only result in this output:
```sql
SELECT * FROM `gossip_menu_option` WHERE `menu_id`= 0 AND `id`= 0;
```
```
menu_id      id  option_icon  option_text               OptionBroadcastTextID  option_id  npc_option_npcflag  action_menu_id  action_poi_id  box_coded  box_money  box_text  BoxBroadcastTextID
-------  ------  -----------  ------------------------  ---------------------  ---------  ------------------  --------------  -------------  ---------  ---------  --------  ------------------
      0       0            0  GOSSIP_OPTION_QUESTGIVER                      0          2                   2               0              0          0          0                             0
```
![condition-editor codition editing](https://cloud.githubusercontent.com/assets/4903600/15361508/6ddf97ba-1d1a-11e6-82c0-b301ce3ccef9.png)

If I may suggest a change, it would be that those 2 options change names if the user selects `SOURCE_TYPE_GOSSIP_MENU` (14), the names of those 2 options can be replaced with [Gossip menu entry] and [Gossip menu text_id]. In the same way, if the user selects `SOURCE_TYPE_GOSSIP_MENU_OPTION` (15), the names could reflect the actual table column names `gossip_menu_option.menu_id` and `gossip_menu_option.id` (you can of course choose to put your own version of the column names there, as long as it makes sense and refers to the actual column names).

***
Looking back at the [Codition editing] tab, may I suggest that the 3 lines below [Condition type] are by default labeled as `ConditionValue1`,`ConditionValue2`,`ConditionValue3` just like in the DB `conditions` table, and that the names change depending on the selected [Condition type]? (You can continue to use the existing behaviour that the ConditionValue2 and ConditionValue3 names are hidden if they are not used by the selected Condition type.)

If I may suggest another detail change for the column names in the [Conditions overview] tab, based on the assumption that Condition-Editor can be made a bit larger or resizeable, is it possible to set the column heading names to be expanded to show the entire name text for all the column header names  by default? (This is only a cosmetic suggestion, since those names are expanded only in text view in SQLyog or other MySQL editors I have used.) :)

**Comment by Discover-** [comment]
TODO: fix tab indexes

**Comment by Discover-** [comment]
TODO: don't use a dash character when a parameter is empty

**Comment by Discover-** [comment]
Made some changes to the condition-editor, please try it again.

**Comment by tkrokli** [comment]
:-) Very well, but every little helps. :+1: Thanks for taking your time, it has been useful so far. :-)
Pulled your latest update and compiled it. ... and it looks great! Thanks for adding access to the buttons! :+1:
 
![condition-editor_window](https://cloud.githubusercontent.com/assets/4903600/15404265/555c34b4-1e05-11e6-9edf-e0897ea6311e.png)

By the way, if you get some time later, do you think you can make the Condition-Editor have the same **width** as the SAI-Editor window? I think that would make users (like me) feel very comfortable with how it is now and be content for quite some time. I love the additions you have made! :smiley:

**Comment by Discover-** [comment]
Creating a new issue for that last request for later.
