### ISSUE TITLE
[Eventparameter] Proposal: Remove eventparameters while using eventtype 61

### ISSUE THREAD

**Issue by Rushor** [Discover-/SAI-Editor#46]
Easiest example can be found here https://github.com/TrinityCore/TrinityCore/commit/03c1769824a7a9559d3f973cdfe3c5db434431e8#commitcomment-20491592

The issue:

If you create a new line with eventtype 61 and if you use the "Link from" button then, the eventparameters will be copied to your new line. eventtype 61 should never contain any values in eventparam1 till eventparam4.

Thank you very much for reading the report :)

**Comment by Discover-** [comment]
I could fix it for you sometime soon, but rolling out a full update is going to take me more time that I don't really have. Would that be okay?

**Comment by Rushor** [comment]
yeah sure :)

**Comment by Discover-** [comment]
I just tried this and the event parameters aren't copied over when using the "Link to" button. Are you sure it wasn't a human error?

**Comment by Rushor** [comment]
hm no, maybe i used an outdated version - i will update to the newest one and test it again

**Comment by Discover-** [comment]
Alright let me know!

**Comment by Rushor** [comment]
okay i cloned the newest version (branch master) and it's the same issue, i will make a video

**Comment by Rushor** [comment]
and the video: https://youtu.be/c8dhw13Rwws

thanks for reviewing it :)

**Comment by Rushor** [comment]
.

**Comment by Discover-** [comment]
Weird, I can't reproduce it myself. Even with LinkFrom. Can you try it without using a world database?

**Comment by Rushor** [comment]
yep without database connection it works fine :o 

```sql
-- <Could not generate name> SAI
SET @ENTRY := 19;
-- No changes to the AIName were made because there is no world database connection.
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,1,1,0,100,0,2000,2000,2000,2000,11,@ENTRY*100+08,0,0,0,0,0,1,0,0,0,0,0,0,0,"Npc - Event - Action (phase) (dungeon difficulty)"),
(@ENTRY,0,1,0,61,0,100,0,0,0,0,0,11,7,0,0,0,0,0,1,0,0,0,0,0,0,0,"Npc - Event - Action (phase) (dungeon difficulty)");
```

**Comment by Discover-** [comment]
Ah I see. I don't have a world database to test it with atm, so it'll be trial and error. I'll give it a shot later.

**Comment by Discover-** [comment]
@Rushor let me know if it works with recent commit. Still don't have a local database for TC myself and I'm clueless as to why it works without a database connection.

I now remember why commenting code is good practice... 😞

**Comment by Rushor** [comment]
@Discover- yes that fix works fine. thank you! <3

**Comment by Discover-** [comment]
Great to hear! Thanks for testing, no problem. 😄
